name: hops_in_the_hangar
description: "Hops in the Hangar is a Flutter layout application."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  google_fonts: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - images/hops_website_header_logo.jpg
    - images/hops_website_header_logo.png
    - images/middletown_aviation_foundation_logo_2026.jpg
